version: "3.2"

services:
  db:
    container_name: db
    image: percona:latest
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: d2Oqadruj9*
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: d2Oqadruj9*
    platform: linux/amd64 #for m1 chip remove it for non amd64 device

  wordpress:
    container_name: wordpress
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - ./wordpress_data:/var/www/html
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: d2Oqadruj9*
      WORDPRESS_DB_NAME: wordpress

  nginx:
    image: nginx:alpine
    ports:
      - '80:80'
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./wordpress_data:/var/www/html
    ports:
      - 8080:80
    links:
      - wordpress

volumes:
  db_data: {}
  wordpress_data: {}
